version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'postgres'
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: app
    image: app
    environment:
      DB_URL: 'jdbc:postgresql://postgres:5432/postgres'
      DB_USERNAME: 'user'
      DB_PASSWORD: 'pass'
    ports:
      - "8080:8080"
    depends_on:
      - postgres